obj-m := disktest.o
  BUILDROOT_DIR := ..
  KDIR := $(BUILDROOT_DIR)/output/target/usr/bin/
  COMPILER := $(BUILDROOT_DIR)/output/host/bin/i686-buildroot-linux-uclibc-gcc
  
  all:
	$(MAKE) -C $(KDIR)
